from pathlib import Path
from datetime import datetime
import shutil, py_compile, re

ROOT=Path(__file__).resolve().parent
DASH=ROOT/"aplus_live_pnl_dashboard.py"
if not DASH.is_file(): raise SystemExit("FAIL: aplus_live_pnl_dashboard.py not found")

stamp=datetime.now().strftime("%Y%m%d_%H%M%S")
backup=ROOT/f"backup_before_main_navbar_v2_{stamp}"
backup.mkdir(parents=True,exist_ok=False)
shutil.copy2(DASH,backup/DASH.name)

NAV='<div id="aplus-main-nav" style="padding:12px 20px;display:flex;gap:10px;flex-wrap:wrap;border-bottom:1px solid #27334d;background:#0b1020">\n<a href="/" style="padding:9px 14px;border:1px solid #22d3ee;border-radius:9px;color:#9ffcff;text-decoration:none;font-weight:800;background:#0f2730">LIVE TRADING</a>\n<a href="/fno-market-watch" style="padding:9px 14px;border:1px solid #27334d;border-radius:9px;color:#e7eefc;text-decoration:none;font-weight:800;background:#121a2d">F&amp;O MARKET WATCH</a>\n<a href="/sector-performance" style="padding:9px 14px;border:1px solid #27334d;border-radius:9px;color:#e7eefc;text-decoration:none;font-weight:800;background:#121a2d">SECTOR PERFORMANCE</a>\n<a href="/opening-structure" style="padding:9px 14px;border:1px solid #27334d;border-radius:9px;color:#e7eefc;text-decoration:none;font-weight:800;background:#121a2d">OPENING STRUCTURE</a>\n<a href="http://127.0.0.1:8766" style="padding:9px 14px;border:1px solid #27334d;border-radius:9px;color:#e7eefc;text-decoration:none;font-weight:800;background:#121a2d">TECHNICAL ALERTS</a>\n</div>'

try:
    s=DASH.read_text(encoding="utf-8")

    if 'id="aplus-main-nav"' in s:
        print("Navigation bar already installed.")
    else:
        # The main dashboard is generated by a function in this build, rather than
        # a top-level *_HTML variable. Find the HTML fragment that actually contains
        # the main terminal title, while explicitly excluding the auxiliary pages.
        title_positions=[m.start() for m in re.finditer(r'APlus Live Trading Terminal',s)]
        patched=False

        # First method: inject into the source HTML/f-string containing the main title.
        for title in reversed(title_positions):
            # Find the nearest literal <body...> before the title, but stay local.
            window_start=max(0,title-18000)
            segment=s[window_start:title]
            bodies=list(re.finditer(r'<body[^>]*>',segment,re.I))
            if not bodies: continue
            m=bodies[-1]
            body_abs_start=window_start+m.start()
            body_abs_end=window_start+m.end()

            # Reject auxiliary HTML blocks by looking at nearby page identifiers.
            nearby=s[max(0,body_abs_start-5000):title]
            if "APlus F&O Market Watch" in nearby or "APlus Sector Performance" in nearby or "APlus Opening Structure Scanner" in nearby:
                continue

            s=s[:body_abs_end]+NAV+s[body_abs_end:]
            patched=True
            break

        # Second method: inject immediately before the main terminal header div.
        if not patched:
            anchors=[
                '<div class="header"><div><div class="title">APlus Live Trading Terminal',
                '<div class="brand-title">APlus Live Trading Terminal',
                '<h1>APlus Live Trading Terminal',
                'APlus Live Trading Terminal</div>',
            ]
            for a in anchors:
                i=s.find(a)
                if i<0: continue
                nearby=s[max(0,i-5000):i]
                if "FNO_MARKET_WATCH_HTML" in nearby[-1000:] or "SECTOR_PERFORMANCE_HTML" in nearby[-1000:]:
                    continue
                s=s[:i]+NAV+s[i:]
                patched=True
                break

        if not patched:
            # Diagnostic instead of unsafe guessing.
            raise RuntimeError("Main page title found but safe insertion point was not detected")

        DASH.write_text(s,encoding="utf-8")
        py_compile.compile(str(DASH),doraise=True)

except Exception:
    shutil.copy2(backup/DASH.name,DASH)
    print("INSTALL FAILED - original dashboard restored:",backup)
    raise

print("="*82)
print("SUCCESS: MAIN DASHBOARD NAVIGATION BAR V2 INSTALLED")
print("Backup:",backup)
print("LIVE TRADING | F&O MARKET WATCH | SECTOR PERFORMANCE | OPENING STRUCTURE | TECHNICAL ALERTS")
print("Only dashboard presentation was changed. Scanner/trading logic untouched.")
print("="*82)
