"""
paper_trade_journal.py

Persistent journal for CE/PE paper signals generated by the continuous intraday
scanner.  It does not place broker orders and it does not invent fills.

A successful signal is written once, then the symbol/direction lane must either
become non-actionable or disappear from the analysed shortlist long enough to
re-arm.  This prevents the same ENTRY_READY condition from creating a duplicate
paper trade every polling cycle while still allowing a later pullback/re-entry.
"""

from __future__ import annotations
from paper_trade_history_store import sync_history

import csv
import json
import logging
import math
import os
import tempfile
import time
import uuid
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Mapping, Sequence

from telegram_notifier import TelegramPaperTradeNotifier


logger = logging.getLogger(__name__)


class PaperTradeJournal:
    """Persist generated paper option trades and de-duplicate repeated signals."""

    CSV_FIELDS: tuple[str, ...] = (
        "paper_trade_id", "generated_at", "symbol", "direction", "stage",
        "setup_family", "selection_tier", "status", "momentum_score",
        "movement_capture_score", "trend_alignment_score", "clean_trend_score",
        "chase_risk_score", "pivot_state", "recent_move_15m_percent",
        "underlying_entry", "underlying_stop", "underlying_target1",
        "underlying_target2", "underlying_target3", "underlying_risk_percent",
        "option_transaction", "option_type", "option_security_id",
        "trading_symbol", "expiry", "strike", "option_ltp", "bid", "ask",
        "limit_price", "option_stop", "option_target1", "option_target2",
        "option_target3", "lot_size", "lots", "quantity", "total_premium",
        "total_risk", "oi", "volume", "iv", "spread_percent",
        "selection_score", "safety_decision", "safety_block_reasons",
        "safety_warnings", "entry_time", "entry_price", "entry_reason",
        "capital_deployed", "planned_risk_amount", "planned_risk_percent",
        "last_quote_time", "last_option_price", "highest_option_price",
        "lowest_option_price", "mfe_amount", "mae_amount",
        "target1_hit_at", "target2_hit_at", "target3_hit_at",
        "runner_mode", "runner_activated_at", "runner_stop",
        "exit_time", "exit_price", "exit_reason", "holding_seconds",
        "gross_pnl", "estimated_costs", "net_pnl", "return_percent", "result",
    )

    def __init__(
        self,
        *,
        state_dir: Path,
        report_dir: Path,
        rearm_minutes: int = 180,
    ) -> None:
        self.state_dir = Path(state_dir)
        self.report_dir = Path(report_dir)
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.report_dir.mkdir(parents=True, exist_ok=True)
        self.state_path = self.state_dir / "paper_trade_journal.json"
        self.report_json = self.report_dir / "paper_trades_latest.json"
        self.report_csv = self.report_dir / "paper_trades.csv"
        self.rearm_minutes = max(5, int(rearm_minutes))
        self.trading_date = ""
        self.trades: list[dict[str, Any]] = []
        self.lanes: dict[str, dict[str, Any]] = {}
        self.notifier = TelegramPaperTradeNotifier(state_dir=self.state_dir)
        self._load()

    def can_generate(
        self,
        *,
        symbol: str,
        direction: str,
        when: datetime,
    ) -> bool:
        self._ensure_date(when.date())
        key = self._lane_key(symbol, direction)
        if any(
            str(item.get("symbol") or "").upper() == str(symbol).upper()
            and str(item.get("direction") or "").upper() == str(direction).upper()
            and str(item.get("status") or "").upper() == "OPEN"
            for item in self.trades
        ):
            return False
        lane = self.lanes.get(key)
        if not lane:
            return True
        if bool(lane.get("armed", True)):
            return True

        # A generated lane may re-arm only after it has remained genuinely
        # non-actionable for the full configured interval.  Do not use
        # last_seen_at here: that timestamp changes every polling cycle and
        # previously allowed brief signal wobble / polling gaps to create a
        # duplicate trade.
        non_actionable_since = self._parse_time(
            lane.get("non_actionable_since")
        )
        if (
            non_actionable_since is not None
            and not bool(lane.get("last_actionable", True))
            and when - non_actionable_since
            >= timedelta(minutes=self.rearm_minutes)
        ):
            lane = dict(lane)
            lane["armed"] = True
            lane["rearmed_at"] = when.isoformat()
            lane["non_actionable_since"] = None
            self.lanes[key] = lane
            return True

        return False

    def observe_candidate(
        self,
        *,
        symbol: str,
        direction: str,
        stage: str,
        actionable: bool,
        when: datetime,
    ) -> None:
        self._ensure_date(when.date())
        key = self._lane_key(symbol, direction)
        lane = dict(self.lanes.get(key) or {})
        lane.setdefault("armed", True)

        if bool(lane.get("armed", True)):
            # No reset timer is needed while the lane is already eligible.
            lane["non_actionable_since"] = None
        elif actionable:
            # The setup became actionable again before completing the reset
            # interval.  Treat it as the same setup and keep it disarmed.
            lane["non_actionable_since"] = None
        else:
            # Start (or continue) a sustained non-actionable reset interval.
            # A single polling-cycle wobble must never re-arm a traded lane.
            non_actionable_since = self._parse_time(
                lane.get("non_actionable_since")
            )
            if non_actionable_since is None:
                lane["non_actionable_since"] = when.isoformat()
            elif (
                when - non_actionable_since
                >= timedelta(minutes=self.rearm_minutes)
            ):
                lane["armed"] = True
                lane["rearmed_at"] = when.isoformat()
                lane["non_actionable_since"] = None

        lane.update({
            "symbol": str(symbol).upper(),
            "direction": str(direction).upper(),
            "last_stage": str(stage),
            "last_actionable": bool(actionable),
            "last_seen_at": when.isoformat(),
        })
        self.lanes[key] = lane

    def record_trade(
        self,
        *,
        plan: Mapping[str, Any],
        candidate: Mapping[str, Any],
        when: datetime,
    ) -> dict[str, Any]:
        self._ensure_date(when.date())
        symbol = str(plan.get("symbol") or candidate.get("symbol") or "").upper()
        direction = str(plan.get("direction") or candidate.get("direction") or "").upper()
        trade_id = (
            f"PT-{when.strftime('%Y%m%d-%H%M%S')}-"
            f"{symbol}-{uuid.uuid4().hex[:6].upper()}"
        )
        option = self._mapping(plan.get("option_contract"))
        underlying = self._mapping(plan.get("underlying"))
        safety = self._mapping(plan.get("safety_gate"))

        record = {
            "paper_trade_id": trade_id,
            "generated_at": when.isoformat(),
            "symbol": symbol,
            "direction": direction,
            "stage": str(plan.get("stage") or candidate.get("stage") or ""),
            "setup_family": str(plan.get("setup_family") or candidate.get("setup_family") or ""),
            "selection_tier": str(plan.get("selection_tier") or candidate.get("selection_tier") or ""),
            "status": "OPEN",
            "momentum_score": self._number(plan.get("momentum_score")),
            "movement_capture_score": self._number(plan.get("movement_capture_score")),
            "trend_alignment_score": self._number(plan.get("trend_alignment_score")),
            "clean_trend_score": self._number(plan.get("clean_trend_score")),
            "chase_risk_score": self._number(plan.get("chase_risk_score")),
            "pivot_state": str(plan.get("pivot_state") or candidate.get("pivot_state") or ""),
            "recent_move_15m_percent": self._number(plan.get("recent_move_15m_percent")),
            "underlying_entry": self._number(underlying.get("entry")),
            "underlying_stop": self._number(underlying.get("stop_loss")),
            "underlying_target1": self._number(underlying.get("target1")),
            "underlying_target2": self._number(underlying.get("target2")),
            "underlying_target3": self._number(underlying.get("target3")),
            "underlying_risk_percent": self._number(underlying.get("risk_percent")),
            "option_transaction": str(option.get("transaction") or ""),
            "option_type": str(option.get("option_type") or ""),
            "option_security_id": str(option.get("security_id") or ""),
            "trading_symbol": str(option.get("trading_symbol") or ""),
            "expiry": str(option.get("expiry") or ""),
            "strike": self._number(option.get("strike")),
            "option_ltp": self._number(option.get("ltp")),
            "bid": self._number(option.get("bid")),
            "ask": self._number(option.get("ask")),
            "limit_price": self._number(option.get("limit_price")),
            "option_stop": self._number(option.get("stop_loss")),
            "option_target1": self._number(option.get("target1")),
            "option_target2": self._number(option.get("target2")),
            "option_target3": self._number(option.get("target3")),
            "lot_size": self._integer(option.get("lot_size")),
            "lots": self._integer(option.get("lots")),
            "quantity": self._integer(option.get("quantity")),
            "total_premium": self._number(option.get("total_premium")),
            "total_risk": self._number(option.get("total_risk")),
            "oi": self._integer(option.get("oi")),
            "volume": self._integer(option.get("volume")),
            "iv": self._number(option.get("iv")),
            "spread_percent": self._number(option.get("spread_percent")),
            "selection_score": self._number(option.get("selection_score")),
            "safety_decision": str(safety.get("decision") or ""),
            "safety_block_reasons": list(safety.get("block_reasons") or []),
            "safety_warnings": list(safety.get("warnings") or []),
            "entry_time": when.isoformat(),
            "entry_price": self._entry_price(option),
            "entry_reason": self._entry_reason(plan, candidate),
            "capital_deployed": 0.0,
            "planned_risk_amount": self._number(option.get("total_risk")),
            "planned_risk_percent": 0.0,
            "last_quote_time": when.isoformat(),
            "last_option_price": 0.0,
            "highest_option_price": 0.0,
            "lowest_option_price": 0.0,
            "mfe_amount": 0.0,
            "mae_amount": 0.0,
            "target1_hit_at": "", "target2_hit_at": "", "target3_hit_at": "",
            "runner_mode": False, "runner_activated_at": "", "runner_stop": 0.0,
            "exit_time": "", "exit_price": 0.0, "exit_reason": "",
            "holding_seconds": 0, "gross_pnl": 0.0, "estimated_costs": 0.0,
            "net_pnl": 0.0, "return_percent": 0.0, "result": "OPEN",
            "plan": dict(plan),
        }
        entry_price = self._number(record.get("entry_price"))
        quantity = self._integer(record.get("quantity"))
        capital = entry_price * quantity
        if capital <= 0:
            capital = self._number(record.get("total_premium"))
        planned_risk = self._number(record.get("planned_risk_amount"))
        record["capital_deployed"] = round(capital, 2)
        record["planned_risk_percent"] = round(
            planned_risk / capital * 100.0, 4
        ) if capital > 0 else 0.0
        record["last_option_price"] = entry_price
        record["highest_option_price"] = entry_price
        record["lowest_option_price"] = entry_price

        self.trades.append(record)

        key = self._lane_key(symbol, direction)
        lane = dict(self.lanes.get(key) or {})
        lane.update({
            "symbol": symbol,
            "direction": direction,
            "armed": False,
            "last_trade_id": trade_id,
            "last_trade_at": when.isoformat(),
            "last_stage": record["stage"],
            "last_actionable": True,
            "last_seen_at": when.isoformat(),
            "non_actionable_since": None,
            "rearmed_at": None,
        })
        self.lanes[key] = lane
        self.notifier.notify_entry(record)
        return record

    def open_positions(self, when: datetime) -> list[dict[str, Any]]:
        self._ensure_date(when.date())
        return [x for x in self.trades if str(x.get("status") or "").upper() == "OPEN"]

    def update_open_positions(
        self, *, option_quotes: Mapping[str, Any], when: datetime,
        force_close: bool = False, force_close_reason: str = "SESSION_END",
    ) -> list[dict[str, Any]]:
        """Update PAPER positions from real option LTPs; no broker orders."""
        self._ensure_date(when.date())
        closed_now = []
        for trade in self.trades:
            if str(trade.get("status") or "").upper() != "OPEN":
                continue
            sid = str(trade.get("option_security_id") or "")
            raw = option_quotes.get(sid)
            if raw is None:
                try:
                    raw = option_quotes.get(int(sid))
                except (TypeError, ValueError):
                    raw = None
            price = self._quote_price(raw)
            if price <= 0:
                continue
            entry = self._number(trade.get("entry_price"))
            qty = self._integer(trade.get("quantity"))
            if entry <= 0 or qty <= 0:
                continue

            trade["last_quote_time"] = when.isoformat()
            trade["last_option_price"] = round(price, 4)
            high = max(self._number(trade.get("highest_option_price")), price)
            old_low = self._number(trade.get("lowest_option_price"))
            low = min(old_low if old_low > 0 else price, price)
            trade["highest_option_price"] = round(high, 4)
            trade["lowest_option_price"] = round(low, 4)
            trade["mfe_amount"] = round((high - entry) * qty, 2)
            trade["mae_amount"] = round((low - entry) * qty, 2)

            for hit_field, target_field in (
                ("target1_hit_at", "option_target1"),
                ("target2_hit_at", "option_target2"),
                ("target3_hit_at", "option_target3"),
            ):
                target = self._number(trade.get(target_field))
                if target > 0 and price >= target and not trade.get(hit_field):
                    trade[hit_field] = when.isoformat()

            original_stop = self._number(trade.get("option_stop"))
            protected_stop = original_stop
            if trade.get("target1_hit_at"):
                protected_stop = max(protected_stop, entry)
            if trade.get("target2_hit_at"):
                protected_stop = max(protected_stop, entry * 1.08)
            if trade.get("target3_hit_at"):
                if not bool(trade.get("runner_mode")):
                    trade["runner_mode"] = True
                    trade["runner_activated_at"] = when.isoformat()
                runner_floor = entry * 1.15
                gain_trail = entry + max(0.0, high - entry) * 0.70
                protected_stop = max(protected_stop, runner_floor, gain_trail)
                trade["runner_stop"] = round(protected_stop, 4)

            reason = ""
            if protected_stop > 0 and price <= protected_stop:
                reason = (
                    "RUNNER_TRAIL_EXIT" if bool(trade.get("runner_mode"))
                    else ("PROFIT_PROTECTION_EXIT" if protected_stop > original_stop else "OPTION_STOP_LOSS")
                )
            elif force_close:
                reason = force_close_reason
            if reason:
                self._close_trade(trade, when, price, reason)
                closed_now.append(trade)
        return closed_now

    def _close_trade(self, trade: dict[str, Any], when: datetime, exit_price: float, reason: str) -> None:
        entry = self._number(trade.get("entry_price"))
        qty = self._integer(trade.get("quantity"))
        gross = (exit_price - entry) * qty
        capital = self._number(trade.get("capital_deployed"))
        entered = self._parse_time(trade.get("entry_time"))
        holding = max(0, int((when - entered).total_seconds())) if entered else 0
        costs = 0.0  # no fabricated brokerage model
        net = gross - costs
        trade.update({
            "status": "CLOSED", "exit_time": when.isoformat(),
            "exit_price": round(exit_price, 4), "exit_reason": reason,
            "holding_seconds": holding, "gross_pnl": round(gross, 2),
            "estimated_costs": costs, "net_pnl": round(net, 2),
            "return_percent": round(net / capital * 100.0, 4) if capital > 0 else 0.0,
            "result": "WIN" if net > 0 else ("LOSS" if net < 0 else "FLAT"),
        })
        self.notifier.notify_exit(trade)

    @classmethod
    def _entry_price(cls, option: Mapping[str, Any]) -> float:
        for key in ("limit_price", "ask", "ltp"):
            value = cls._number(option.get(key))
            if value > 0:
                return value
        return 0.0

    @staticmethod
    def _entry_reason(plan: Mapping[str, Any], candidate: Mapping[str, Any]) -> str:
        reasons = plan.get("reasons") or candidate.get("reasons") or []
        detail = " | ".join(str(x) for x in reasons) if isinstance(reasons, (list, tuple)) else str(reasons or "")
        return " | ".join(x for x in (
            str(plan.get("stage") or candidate.get("stage") or ""),
            str(plan.get("setup_family") or candidate.get("setup_family") or ""),
            detail,
        ) if x)

    @classmethod
    def _quote_price(cls, raw: Any) -> float:
        if not isinstance(raw, Mapping):
            return 0.0
        for key in ("last_price", "ltp", "LTP"):
            value = cls._number(raw.get(key))
            if value > 0:
                return value
        return 0.0

    def summary(self, when: datetime) -> dict[str, Any]:
        self._ensure_date(when.date())
        open_trades = [x for x in self.trades if str(x.get("status")).upper() == "OPEN"]
        closed = [x for x in self.trades if str(x.get("status")).upper() == "CLOSED"]
        return {
            "trading_date": self.trading_date,
            "paper_trades_today": len(self.trades),
            "open_positions": len(open_trades),
            "closed_trades": len(closed),
            "wins": sum(1 for x in closed if self._number(x.get("net_pnl")) > 0),
            "losses": sum(1 for x in closed if self._number(x.get("net_pnl")) < 0),
            "gross_pnl": round(sum(self._number(x.get("gross_pnl")) for x in closed), 2),
            "net_pnl": round(sum(self._number(x.get("net_pnl")) for x in closed), 2),
            "journal_state_file": str(self.state_path),
            "journal_report_json": str(self.report_json),
            "journal_report_csv": str(self.report_csv),
            "rearm_minutes": self.rearm_minutes,
        }

    def flush(self) -> bool:
        """Persist journal files without terminating the scanner."""
        sync_history(self.report_dir, self.trades)
        state_payload = {
            "trading_date": self.trading_date,
            "rearm_minutes": self.rearm_minutes,
            "lanes": self.lanes,
            "trades": self.trades,
        }
        ok = True
        targets = (
            ("journal_state", lambda: self._atomic_json(self.state_path, state_payload), self.state_path),
            ("paper_trades_json", lambda: self._atomic_json(
                self.report_json,
                {"trading_date": self.trading_date, "paper_trades": self.trades},
            ), self.report_json),
            ("paper_trades_csv", lambda: self._write_csv(self.report_csv, self.trades), self.report_csv),
        )
        for label, writer, path in targets:
            try:
                writer()
            except Exception as exc:
                ok = False
                logger.warning(
                    "Paper journal persistence failed but scanner will continue "
                    "(target=%s path=%s error=%s: %s)",
                    label, path, type(exc).__name__, exc,
                )
        return ok

    def _ensure_date(self, value: date) -> None:
        key = value.isoformat()
        if self.trading_date != key:
            self.trading_date = key
            self.trades = []
            self.lanes = {}

    def _load(self) -> None:
        if not self.state_path.exists():
            return
        try:
            payload = json.loads(self.state_path.read_text(encoding="utf-8"))
            trades = payload.get("trades") or []
            lanes = payload.get("lanes") or {}
            self.trading_date = str(payload.get("trading_date") or "")
            self.trades = [dict(item) for item in trades if isinstance(item, Mapping)]
            self.lanes = {
                str(key): dict(value)
                for key, value in lanes.items()
                if isinstance(value, Mapping)
            }
        except Exception:
            self.trading_date = ""
            self.trades = []
            self.lanes = {}

    @staticmethod
    def _lane_key(symbol: str, direction: str) -> str:
        return f"{str(symbol).strip().upper()}|{str(direction).strip().upper()}"

    @staticmethod
    def _mapping(value: Any) -> Mapping[str, Any]:
        return value if isinstance(value, Mapping) else {}

    @staticmethod
    def _parse_time(value: Any) -> datetime | None:
        try:
            return datetime.fromisoformat(str(value or ""))
        except Exception:
            return None

    @staticmethod
    def _number(value: Any) -> float:
        try:
            number = float(value or 0.0)
        except (TypeError, ValueError, OverflowError):
            return 0.0
        return number if math.isfinite(number) else 0.0

    @staticmethod
    def _integer(value: Any) -> int:
        try:
            return int(float(value or 0))
        except (TypeError, ValueError, OverflowError):
            return 0

    @staticmethod
    def _replace_with_retry(
        temporary: Path,
        path: Path,
        *,
        attempts: int = 7,
        initial_delay: float = 0.05,
    ) -> None:
        delay = max(0.01, float(initial_delay))
        attempts = max(1, int(attempts))
        last_error = None
        for attempt in range(1, attempts + 1):
            try:
                os.replace(temporary, path)
                return
            except (PermissionError, OSError) as exc:
                last_error = exc
                if attempt >= attempts:
                    break
                logger.warning(
                    "Atomic replace retry %s/%s for %s after %s: %s",
                    attempt, attempts, path, type(exc).__name__, exc,
                )
                time.sleep(delay)
                delay = min(delay * 2.0, 0.80)
        if last_error is not None:
            raise last_error
        raise RuntimeError(f"Atomic replace failed for {path}")


    @classmethod
    def _write_csv(cls, path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, temp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
        os.close(fd)
        temporary = Path(temp_name)
        try:
            with temporary.open("w", newline="", encoding="utf-8") as handle:
                writer = csv.DictWriter(handle, fieldnames=list(cls.CSV_FIELDS))
                writer.writeheader()
                for row in rows:
                    payload = {field: row.get(field, "") for field in cls.CSV_FIELDS}
                    for field in ("safety_block_reasons", "safety_warnings"):
                        value = payload.get(field)
                        if isinstance(value, (list, tuple, set)):
                            payload[field] = " | ".join(str(item) for item in value)
                    writer.writerow(payload)
                handle.flush()
                os.fsync(handle.fileno())
            cls._replace_with_retry(temporary, path)
        finally:
            temporary.unlink(missing_ok=True)

    @classmethod
    def _atomic_json(cls, path: Path, payload: Mapping[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, temp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
        os.close(fd)
        temporary = Path(temp_name)
        try:
            with temporary.open("w", encoding="utf-8") as handle:
                json.dump(payload, handle, indent=2, ensure_ascii=False)
                handle.flush()
                os.fsync(handle.fileno())
            cls._replace_with_retry(temporary, path)
        finally:
            temporary.unlink(missing_ok=True)

